# Changes here will be overwritten by Copier
_commit: 0b36711
_src_path: https://codeberg.org/Fresh2dev/copier-f2dv-project.git
author_email: hello@f2dv.com
author_name: Donald Mellenbruch
ci_domain_name: lokalhost.net
docs_slides_url: https://www.f2dv.com/s/tuiview
docs_url: https://www.f2dv.com/r/tuiview
funding_url: https://www.f2dv.com/fund
home_domain: f2dv.com
home_page: https://www.f2dv.com
is_minimal: false
is_python: true
license_type: GPLv3
package_name: tuiview
project_description: A TUI for every CLI
project_name: tuiview
python_version: '3.8'
repo_mirror: https://www.f2dv.com/r/tuiview
repo_name: fresh2dev/tuiview
repo_owner: fresh2dev
repo_url: https://www.github.com/fresh2dev/tuiview

