kind: template
load: hostbutter.jsonnet
data:
  domains: >-
    ["lokalhost.net"]
  domainTriggers: >-
    {
      "lokalhost.net": {}
    }
  domainClusterMap: >-
    {}
  publishRegistries: >-
    {}
  secrets: >-
    []
  secretFiles: >-
    {
      "ENV_FILE": ".env"
    }
  volumes: >-
    []
  beforeSteps: >-
    [
      {
        "name": "py-test",
        "image": "registry.lokalhost.net/fresh2dev/mykefiles:a43f1d5",
        "environment": {
          "PIP_CONF": {"from_secret": "PIP_CONF"},
          "MYKE_MODULE": "mykefiles.python"
        },
        "commands": [
          "mkdir -p ~/.config/pip && echo \"$PIP_CONF\" > ~/.config/pip/pip.conf",
          "myke py-install",
          "myke py-reports",
          "myke py-build"
        ],
        "when": {}
      }
    ]
  afterSteps: >-
    []
  finalSteps: >-
    [
      {
        "name": "py-build-package",
        "image": "registry.lokalhost.net/fresh2dev/mykefiles:a43f1d5",
        "environment": {
          "PYPI_CREDS": {"from_secret": "PYPI_CREDS"},
          "PIP_CONF": {"from_secret": "PIP_CONF"},
          "MYKE_MODULE": "mykefiles.python"
        },
        "commands": [
          "echo \"$PYPI_CREDS\" > ~/.pypirc",
          "mkdir -p ~/.config/pip && echo \"$PIP_CONF\" > ~/.config/pip/pip.conf",
          "myke py-version-set --repository lokalhost",
          "myke py-build"
        ],
        "when": {}
      },
      {
        "name": "py-publish-sandbox",
        "image": "registry.lokalhost.net/fresh2dev/mykefiles:a43f1d5",
        "environment": {
          "PYPI_CREDS": {"from_secret": "PYPI_CREDS"},
          "PIP_CONF": {"from_secret": "PIP_CONF"},
          "TWINE_CERT": "/etc/ssl/certs/ca-certificates.crt",
          "MYKE_MODULE": "mykefiles.python"
        },
        "commands": [
          "echo \"$PYPI_CREDS\" > ~/.pypirc",
          "mkdir -p ~/.config/pip && echo \"$PIP_CONF\" > ~/.config/pip/pip.conf",
          "myke py-publish --repository lokalhost"
        ],
        "when": {}
      },
      {
        "name": "py-publish-dev",
        "image": "registry.lokalhost.net/fresh2dev/mykefiles:a43f1d5",
        "environment": {
          "PYPI_CREDS": {"from_secret": "PYPI_CREDS"},
          "PIP_CONF": {"from_secret": "PIP_CONF"},
          "TWINE_CERT": "/etc/ssl/certs/ca-certificates.crt",
          "MYKE_MODULE": "mykefiles.python"
        },
        "commands": [
          "echo \"$PYPI_CREDS\" > ~/.pypirc",
          "mkdir -p ~/.config/pip && echo \"$PIP_CONF\" > ~/.config/pip/pip.conf",
          "myke py-publish --repository codeberg"
        ],
        "when": {
          "ref": ["refs/heads/dev", "refs/heads/main", "refs/tags/*"]
        }
      },
      {
        "name": "py-publish-test",
        "image": "registry.lokalhost.net/fresh2dev/mykefiles:a43f1d5",
        "environment": {
          "PYPI_CREDS": {"from_secret": "PYPI_CREDS"},
          "PIP_CONF": {"from_secret": "PIP_CONF"},
          "TWINE_CERT": "/etc/ssl/certs/ca-certificates.crt",
          "MYKE_MODULE": "mykefiles.python"
        },
        "commands": [
          "echo \"$PYPI_CREDS\" > ~/.pypirc",
          "mkdir -p ~/.config/pip && echo \"$PIP_CONF\" > ~/.config/pip/pip.conf",
          "myke py-publish --repository testpypi"
        ],
        "when": {
          "ref": ["refs/tags/*"]
        }
      },
      {
        "name": "py-publish-prod",
        "image": "registry.lokalhost.net/fresh2dev/mykefiles:a43f1d5",
        "environment": {
          "PYPI_CREDS": {"from_secret": "PYPI_CREDS"},
          "PIP_CONF": {"from_secret": "PIP_CONF"},
          "TWINE_CERT": "/etc/ssl/certs/ca-certificates.crt",
          "MYKE_MODULE": "mykefiles.python"
        },
        "commands": [
          "echo \"$PYPI_CREDS\" > ~/.pypirc",
          "mkdir -p ~/.config/pip && echo \"$PIP_CONF\" > ~/.config/pip/pip.conf",
          "myke py-publish --repository pypi"
        ],
        "when": {
          "ref": ["refs/tags/*"]
        }
      }
    ]
  extraObjects: >-
    [
      {
        "kind": "secret",
        "name": "PYPI_CREDS",
        "get": {
          "path": "secret/data/hostbutter/global",
          "name": "PYPI_CREDS"
        }
      },
      {
        "kind": "secret",
        "name": "PIP_CONF",
        "get": {
          "path": "secret/data/hostbutter/global",
          "name": "PIP_CONF"
        }
      }
    ]
